version: '3.9'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./frontend/logs:/var/log/nginx
    networks:
      - mycloud-network

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=youremail@example.com
    networks:
      - mycloud-network

  frontend:
    build:
      context: ../MyCloud_Frontend
      dockerfile: Dockerfile
    container_name: mycloud_frontend
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - VIRTUAL_HOST=aim-cloud.ru
      - LETSENCRYPT_HOST=aim-cloud.ru
      - LETSENCRYPT_EMAIL=youremail@example.com
      - VIRTUAL_PORT=80
    networks:
      - mycloud-network

  backend:
    build:
      context: ../MyCloud_Backend
    container_name: mycloud_backend
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - ../MyCloud_Backend/.env.prod
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mycloud-network
    environment:
      - ENV=production
      - VIRTUAL_HOST=aim-cloud.ru
      - LETSENCRYPT_HOST=aim-cloud.ru
      - LETSENCRYPT_EMAIL=youremail@example.com
      - VIRTUAL_PORT=8000

  db:
    image: postgres:15-alpine
    container_name: mycloud_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mycloud_db
      - POSTGRES_USER=mycloud_admin
      - POSTGRES_PASSWORD=5tr0ngP@ss
    networks:
      - mycloud-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mycloud_admin -d mycloud_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  mycloud-network:
    driver: bridge
