#version: '3.9'

services:
  nginx:
    build:
      context: ../MyCloud_Frontend
      dockerfile: Dockerfile
    container_name: mycloud_nginx
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - mycloud-network

  backend:
    build:
      context: ../MyCloud_Backend
    container_name: mycloud_backend
#    ports:
#      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - ../MyCloud_Backend/.env.prod
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mycloud-network
    environment:
      - ENV=production

  db:
    image: postgres:15-alpine
    container_name: mycloud_db
    restart: always
#    ports:
#      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mycloud_db
      - POSTGRES_USER=mycloud_admin
      - POSTGRES_PASSWORD=5tr0ngP@ss
    networks:
      - mycloud-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U mycloud_admin -d mycloud_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  mycloud-network:
    driver: bridge